"""
Django settings for dx_movie project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_gw=vhwsbpmiin6epw%ktbum1lgevoz9%ndwqs1k9q)rkvr+5-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'movie',
    'rest_framework',
    'django_filters',
    'djoser',
    'account',
    'trade',
    'django_celery_beat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dx_movie.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [], #前后端分离项目这里不用配置模版路径
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dx_movie.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'drf_movie',
        'USER': 'root',
        'PASSWORD': 'hwk123456',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'
LOCALE_PATHS = [
    Path(BASE_DIR).joinpath('locale'),
]

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 12,
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# 邮箱配置，授权码：bklwozhvvbdacbaa
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' # 邮箱后端
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True # 使用SSL
EMAIL_HOST_USER = '492193247@qq.com'
EMAIL_HOST_PASSWORD = 'bklwozhvvbdacbaa'
DEFAULT_FROM_EMAIL = '492193247@qq.com'

# 配置jwt
SIMPLE_JWT = {
   'AUTH_HEADER_TYPES': ('JWT',),
   'ACCESS_TOKEN_LIFETIME':timedelta(minutes=60),
   'REFRESH_TOKEN_LIFETIME':timedelta(days=14),
}

# Djsoer配置
DJOSER = {
    'USER_ID_FIELD':'username',
    'LOGIN_FIELD':'email',
    'SEND_ACTIVATION_EMAIL':True, # 发送激活邮件
    'ACTIVATION_URL': 'activate/{uid}/{token}', # 激活链接
    'SEND_CONFIRMATION_EMAIL':True, # 发送确认邮件
    'PASSWORD_RESET_CONFIRM_URL':'password-reset-confirm/{uid}/{token}', # 重置密码链接
    'PASSWORD_RESET_CONFIRM_RETYPE':True, # 重置密码确认重置
    'PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND':True, # 重置密码显示邮箱不存在
    'SET_PASSWORD_RETYPE':True, # 设置密码确认重置
    'SERIALIZERS': {
        'user_create': 'account.serializers.CustomUserCreateSerializer', # 用户创建序列化器
        'current_user': 'account.serializers.CustomUserSerializer', # 当前用户序列化器
    }
}

# 配置支付宝
ALIPAY_SERVER_URL = 'https://openapi-sandbox.dl.alipaydev.com/gateway.do' #支付宝网关地址
ALIPAY_APP_ID = '9021000149648676' #支付宝APPID
ALIPAY_APP_PRIVATE_KEY = 'MIIEpQIBAAKCAQEAzhRBJlGlipeBPWYy7chbIos7vwNRluevPa68VhvOspiIrSrvNiq4XJ4678OyMWxjznv3AH6IGGjFW8c9mDaPZJ+J7ZN5GC2BbfvF4gUekpqzrVBMzbM5HJPZM4+de1GmdFhpcn4knptFla4cLARNtOJBJheDmiYcVZqVcY6BNzv05nQsqswcg2u1hbgSwJ3lpzuz2g6GGiLQX+df7noa6BB3YoLP35gXJ9tgbIMKA0qIEN7CEZJobHlSYDRqZ0VcYoMTn4zuTONcnzXSSWf3hFp8xxPPvUJpSc+p1UXPpNNjMZ1xJecw6xYFdsOcHrwxGyhs3gu23m4Xlws1DmfLkQIDAQABAoIBAAywHI7CaiHNUCy6lRokws+uqOAK0UQsQZLXpkra7W/7ija3NQEtwioZp+FJODhoxwBYi42hPLncAYK0EqvDeDKmy/Qvpz4A1z4xSS6wSACYu8VI82GazkJfK/lLt1N3ZHs3Uk61S4XkY3ViweNH5IzlfUNeIUElZYszuE3Ei1oeH5sVvIVRtcSczoUoCtXED8T0cm2Dh9BXpptnPwDFOQzfKzzBH/TlchBioUkqWgcMJphiqgWxMrMSynTm/Nj+xx3krzc5H79LFKKYT1iJNWgFnZkbfqqqut1WRtR/RlUzcAFf2dveGDnt/tEqSh55VwIIjSCOeSA8hYWvI9wFUx0CgYEA7LwTOQynd6Ig0D4FrCutiu5irfxFvSW9GwWXZUdS/eNy1+74igfojINkfXh124Vzy+JZZd3h1VoUfeCupIaBKZ3vYZ3hlHH0YzWNgIRIoeSlltRPrkEzxN7XYdgRXytdtadz92sZ3DLqsSob7cfD83lalQp6TuHZN5zkU+LNguMCgYEA3tmHO+C+33uN0k/487IA0Os1kI8txLZBW5MrF4TxEdiB9DfxQxzxJWUqdNN2vdoDS8lv05Ugh6JyLu0wxdDNU8eyxsJEMQif7TA+TotJ+RtLuxPAZuINJjjGqB9U3tacfjjFeLuAvz3lnpVK6BbsugYTLZjX6eBvNDgIM4L0XfsCgYEAgEcJQ4iP1kuL7EsvV7PzPa0e25gvUeb5KYNGHiMf3WM5/7gGBQV0BW/NLA/yDRmrPXdRadlpXeqJ4Au3ln8rzhk+dW7PpVh6TKfgHRuRH+h9sdUpuAqsuqjlnKcwApnFFYG/XPoz8RXGBmoC6D2u+GdxpgEfdU78HR5uuuXS5nECgYEA0LYEPOUxftcVrUovC/XDY+dWRGyEXf6f2adMrXtZ1+/hThvyvntlsjM8fyvpwsdjXOBs9kltrPpMXHzSuAHlu7iFTDd3bED6n0cWo7M6da7Fz5EhGnpN/GUiUST+9LEk4eZDs95QJ0xOOKbz/8gwr8yuu36xgR4sqEhuDehw+28CgYEAkfEtMLjwRG8e1ksRw1KAuqF/mvKUFnDKPbF8q2jyU7j8kuq41BMNi3Kv9CZNgwRNUiFt6na6PEyk1mdqEZIQy446zkfcS6TBbaC7ymdTrb9zvN6C4KkHNH/u6GPqpfqc7TL+Ye7ocg+qqo6e8BhBCFgSPmgJXx+GgNi79N9Ni+o=' # 支付宝应用私钥
ALIPAY_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqzEpHtDtSYuByO+dqQXCycrTqL1kXnCsg7rs+Nl2zsKV3vths7FdVaD51LdzIDE9xF0Okn60LE90+RAv66oLrueYvyJzZhH9vgPX8f6/LsxJiPT0W+3KHKr8m8kQGO/sZY7hbcUtnP7KA1tkFghHVPOPkY1iSgO7g8pYuwVYA96dukclQyQjXtSfbt76rADKdG6r4kxPwS46Tfj5fFcv0b23SuWFB15f186HDZMQA/S/RzyFRsQ4qlrEcM3IsIZ1HXOHSSrvQtl0iet86Z91I4KDmSjpAdWl41AHGpeXpST5upGiSzT7A0eQ7tMxuaVa1yWnOJ6faeSzQfh1HqF43QIDAQAB' # 支付宝公钥

# return url
ALIPAY_RETURN_URL = 'http://6b8b7dc3.r9.cpolar.top/orders/'

# notify url
ALIPAY_NOTIFY_URL = 'http://6b8b7dc3.r9.cpolar.top/api/callback/'

# seller_id
ALIPAY_SELLER_ID = '2088721069822685'

# 配置Celery Configuration Options
CELERY_BROKER_URL = 'redis://localhost:6379/0' #用redis作为celery的消息代理
CELERY_RESULT_BACKEND = 'redis://localhost:6379/1' #任务结果存放
CELERY_TIMEZONE = "Asia/Shanghai"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
